### PR TITLE
Add mozlog for console logging and debugging

### PR DESCRIPTION
**Pull request by davehunt**
Would you mind taking a quick look over this @jonallengriffin? We have noticed the perf tests taking a lot longer on master recently but with no regressions in the metrics. The additional debug logs should help to determine where time is being spent.

### CODE REVIEW

**Comment by jonathanagriffin** [comment]
Looks good to me.

**Comment by jonallengriffin** [comment]
> Looks good to me.

whoops, was using the wrong account :_

**Comment by davehunt** [comment]
heh, thanks... :)

**Comment by davehunt** [comment]
This was merged in a3b130a2eb0a51d8521cb33369f2d0b237aeb06b

**Pull request closed without merging**
