### PR TITLE
Add script to process mozPerfDuration results

### PR DESCRIPTION
**Pull request by jonallengriffin**
This refactors b2gperf.py so I could re-use most of its functionality in a new script, mozperf.py, which just processes the output of 'make test-perf' and submits it to datazilla.

### CODE REVIEW

**Comment by davehunt** [comment]
Looks mostly fine, however mozPerfDuration requires but does not use Marionette. Should we remove that dependency? I also think it's a little unclear from the outside what the difference between B2GPerf and MozPerfHandler. Is this data going to be submitted to the b2g project? I'm not clear on the distinction between these two harnesses.

**Comment by jonallengriffin** [comment]
mozperf.py does use Marionette - look at the bottom of the file.

MozPerfHandler is designed to parse the output of 'make test-perf', and post the results to https://datazilla.mozilla.org/b2g/.  It uses a different metric, 'mozperfduration', so should be displayed separately from the current data.  It doesn't run any tests, it just parses results and uploads to datazilla.

Originally I started writing a separate script for this, but it duplicated so much code already in b2gperf.py I thought a refactor and inherit approach made more sense.

B2GPerf is now a base class which is used both by this and by the current "cold_load_time" runner.  To make things cleaner, we could make a base class called DatazillaPerf, or something, which just sets up the datazilla fields and posts to datazilla, and make both B2GPerf and MozPerfHandler inherit from this.

**Comment by jonallengriffin** [comment]
I've tried to make this a little cleaner by making a DatazillaPerfPoster class that both B2GPerfRunner and MozPerfHandler extend.

**Comment by davehunt** [comment]
I like these changes. I still don't see where MozPerfHandler uses Marionette (I can see that a session is started, but afaict it's never used). I'll make you a contributor so you can push directly to this repository without need for review (but feel free to request reviews).

I have a feeling there will be a bit more restructuring going on with regards to the scroll performance tests recently mentioned. This is a very organic harness. :)

**Comment by jonallengriffin** [comment]
Marionette is used by the base class that MozPerfHandler is derived from; we pass it in to the constructor, and then it's used in the base class's **init**:

```
    mac_address = self.marionette.execute_script('return navigator.mozWifiManager && navigator.mozWifiManager.macAddress;')
```

I won't merge this until we have a green run on the Jenkins trial job, in order to avoid muddying the waters.

**Comment by davehunt** [comment]
Ah.. I completely missed that! :) I'll be looking at the trial job today. Thanks.

**Comment by davehunt** [comment]
I've pushed a fixed version of b2gperf, and updated all jobs to use it. Everything seems to be running smoothly.

**Comment by jonallengriffin** [comment]
I'm going to merge this and will watch Jenkins for breakage.

**Comment by davehunt** [comment]
It won't affect the b2gperf jobs, as they use a pinned version from PyPI :)

**Pull request merged**
